### ISSUE TITLE
non-zero z component of x and y vectors in POSCAR

### ISSUE THREAD

**Issue by ondrejkrejci** [Open-Catalyst-Project/Open-Catalyst-Dataset#49]
Dear OCP team!

I have recently tried to redo some of your **VASP** calculations with different bulks. I have succeeded to create around 80 random structures, that are important for our research and they are not in OCP. But what stroke me was that 7 of these structures did not pass through K-points creation in **VASP** and crashed immediately - for both `adslab` and `surface`. I looked into the POSCAR files and have found out, that all of them has one of the _x_ or _y_ vector has its _z_ component, super close to zero, but still not zero - like the last two numbers in following example:
```
     9.9316839878664318    0.0000000000000000    0.0000000000000006
    -4.9658419939332203    8.6010906358514703    0.0000000000000013
     0.0000000000000000    0.0000000000000000   32.4367440757903509
```
Have you ever noticed this? Should not be some kind of "rounding" introduced to the slab-making procedure?

I have also noticed, that some of the prepared slabs have generally non-zero _z_ component of the _x_ and _y_ lattice vectors - e.g.:
```
     8.6083619191597496    0.0000000000000000   -0.2955649211359311
    -0.3495286014526182   12.9325431982279824    3.1305913613413510
     0.0000000000000000    0.0000000000000000   39.9319548081576130
```
Is there some reason for these? as I have always rather rotated my atoms and left these to be exactly "0.0". I guess it was mainly because I was learned to do that and also other post-processing (simulations of Scanning Probe/X-ray related experiments).
By the way, what is your exact **VASP** version, so my data could be directly comparable to yours?
Thank you for your answers!
Ondrej

**Comment by ondrejkrejci** [comment]
Update on the first question/comment: I've found out, that the setting the small non-zero parts exactly to zero is not solving the problem,as I still obtain `VERY BAD NEWS! internal error in subroutine SGRCON`. As I have almost 10% of these systems, which are not working I want to ask, if you got the same amount of these errors, or is the problem just on my side (VASP version/compilation, different substrates ... )?
The other 2 questions are still relevant.
Thank you for your answers!
Ondrej

**Comment by sidgoyal78** [comment]
Hi @ondrejkrejci 
Thanks for your interest!
The exact version of VASP that we are using is 5.4.4. We will have to analyze the outputs of the calculations to give provide an estimate of systems where we encountered the warning "VERY BAD NEWS ...".

**Comment by ondrejkrejci** [comment]
Hi @sidgoyal78
thank you for your answer! Good, I am using the same version.
I am still curious, if it is only my problem, or if it is general.
