### ISSUE TITLE
Generating slabs for `mp-14928` takes too long

### ISSUE THREAD

**Issue by abhshkdz** [Open-Catalyst-Project/Open-Catalyst-Dataset#71]
Generating slabs for `MnSc2Se4 (mp-14928)` is very slow.  The HTTP request times out on the demo, and takes `1min 27s ± 523 ms` when done manually using `ocdata`:

```python
from ocdata.core import Bulk, Slab

bulk = Bulk(bulk_src_id_from_db="mp-14928")
slabs = Slab.from_bulk_get_all_slabs(bulk)
```

Is there anything we can do to speed this up?

**Comment by abhshkdz** [comment]
Looks like majority of time is spent in this [`get_primitive_structure`](https://github.com/materialsproject/pymatgen/blob/v2023.7.17/pymatgen/core/structure.py#L2213) call:

![image](https://github.com/Open-Catalyst-Project/Open-Catalyst-Dataset/assets/1156489/2a4e4fec-672e-4f91-a1f1-31e9db33ad6f)

**Comment by mshuaibii** [comment]
Not much we can do on our end. One solution is to precompute these so we dont have to create them from scratch all the time. Closing for now.
