### ISSUE TITLE
User-defined slab

### ISSUE THREAD

**Issue by quanp** [Open-Catalyst-Project/Open-Catalyst-Dataset#76]
Dear developers,

I am wondering, instead of generating slabs from bulk, it is possible to provide a user-defined slab directly? For example, I would like to read a slab from Vasp POSCAR input?

Thanks.

**Comment by mshuaibii** [comment]
Yes you can, if you read in the POSCAR as an ASE atoms object you can feed it into https://github.com/Open-Catalyst-Project/Open-Catalyst-Dataset/blob/176306367f2d65044c462d7efe2f7da400ed5b87/ocdata/core/slab.py#L47.
