### ISSUE TITLE
Construct a pkl file for new adsorbates?

### ISSUE THREAD

**Issue by icemountain555** [Open-Catalyst-Project/Open-Catalyst-Dataset#80]
Hi,
Thanks so much for your fantastic work on Open-Catalyst-Dataset.
I noticed that you used the pkl file to obtain the adsorbate object in the [README.md](https://github.com/Open-Catalyst-Project/Open-Catalyst-Dataset/blob/main/README.md#usage) .
![image](https://github.com/Open-Catalyst-Project/Open-Catalyst-Dataset/assets/141994752/e4b4a244-8e3a-4667-bcbc-d6ce3569e7a2)

If I want to use your model to predict the adsorption energy of some new adsorbents (such as benzene) on catalysts, **how can I construct a new pkl file?** Or is there another way?

BTW, if I want to construct a new bulk, is there any method？

Finally, how to use the [ML relaxations(ocpmodels) way](https://github.com/Open-Catalyst-Project/Open-Catalyst-Dataset/blob/main/ocdata_workflow.png) to predict the energy?

Thanks！

**Comment by mshuaibii** [comment]
Closing. Answered at https://discuss.opencatalystproject.org/t/construct-a-pkl-file-for-new-adsorbates/434.
