### ISSUE TITLE
Question about POTCAR file

### ISSUE THREAD

**Issue by mjrs33** [Open-Catalyst-Project/Open-Catalyst-Dataset#84]
Hi, I have a question about the POTCARs used in the VASP calculation.

According to `write_vasp_input_files`, POTCARs are generated by ASE without specifying the POTCAR type.
In this case, POTCARs are created in the `ase.calculators.vasp.setups.get_default_setups()["minimal"]` settings, and include POTCARs that are not recommended by VASP (for example, in Li, VASP's recommendation is Li_sv, but the above setting creates Li).

Is the POTCAR used in the OC20 data made with the "minimum" setting rather than the "recommended" setting?

**Comment by mshuaibii** [comment]
Yes, the "minimal" set was used for OC20.
